### PR TITLE
Make `git-xl` installable with pip

### PR DESCRIPTION
**Pull request by MilesCranmer**
I threw this together so I could use it locally but realized others might find it useful as well, so here you go. This makes `git-xl` installable with `pip`, and usable on macOS and linux without the need for `pyinstaller`.

With this change, you can do:
```
pip install git+https://github.com/xlwings/git-xl
```
to install this package directly from git into Python's packages, and then:
```
python -m gitxl install
```
to install it (or run any of the other CLI commands).

### CODE REVIEW

**Comment by fzumstein** [comment]
Thanks! I like the idea, but the tests are currently failing: https://github.com/xlwings/git-xl/actions/runs/3409486259/jobs/5671317549

Also, I'd probably go ahead and use the more future proof way of building packages based on `pyproject.toml` instead of `setup.py`.

**Comment by fzumstein** [comment]
Also, this can be turned into a proper cli command (`xltrail` instead of `python -m gitxl`) and the version string shouldn't be hardcoded, but will be replaced by the CI pipeline...

I can look into these things, but just don't have a lot of time right now.

**Comment by watercrossing** [comment]
Hey,

I have added support for cli commands and installation with [pipx](https://pypa.github.io/pipx/) in my fork (https://github.com/watercrossing/git-xl). 
This makes installation even easier:
`pipx install git+https://github.com/watercrossing/git-xl.git` (later this would be just `pipx install git-xl` to install from pypi,
and then `git-xl install`.

Perhaps @MilesCranmer can merge my commit into their repo to add it to this PR?

**Comment by MilesCranmer** [comment]
Hey @watercrossing,
Feel free to create a new PR with your + my commits (if desired)! I unfortunately don't have time to clean up this one, and ended up switching to an alternate solution anyways.
Cheers,
Miles

**Comment by Jython1415** [comment]
> I unfortunately don't have time to clean up this one, and ended up switching to an alternate solution anyways.

@MilesCranmer Might I ask what this alternate solution was? I'm trying to find a good way to version control excel files on a Mac.

**Pull request closed without merging**
